# Kanagawa Paper Ink (Lightened)
# Reference: https://github.com/thesimonho/kanagawa-paper.nvim/blob/master/extras/wezterm/kanagawa-paper-ink.toml
# Reference: https://github.com/sho-87/kanagawa-paper.nvim/blob/master/extras/alacritty_kanagawa_paper.yml

[colors]
background = "#1F1F28"
foreground = "#DCD7BA"
cursor_bg = "#c4b28a"
cursor_border = "#c4b28a"
cursor_fg = "#1F1F28"
selection_bg = "#658594"
selection_fg = "#C8C093"
split = "#8992a7"
compose_cursor = "#8ea49e"
scrollbar_thumb = "#363646"

ansi = [
  "#0d0c0c",
  "#c4746e",
  "#8a9a7b",
  "#c4b28a",
  "#8ba4b0",
  "#a292a3",
  "#8ea4a2",
  "#C8C093",
]
brights = [
  "#a6a69c",
  "#E46876",
  "#87a987",
  "#E6C384",
  "#7FB4CA",
  "#938AA9",
  "#7AA89F",
  "#c5c9c5",
]

[colors.indexed]
16 = "#b6927b"
17 = "#ff5d62"

[colors.tab_bar]
background = "#8a9a7b"
inactive_tab_edge = "#658594"

[colors.tab_bar.active_tab]
fg_color = "#c4b28a"
bg_color = "#1F1F28"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#9e9b93"
bg_color = "#2A2A37"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#a292a3"
bg_color = "#1F1F28"

[colors.tab_bar.new_tab]
fg_color = "#9e9b93"
bg_color = "#2A2A37"

[colors.tab_bar.new_tab_hover]
fg_color = "#a292a3"
bg_color = "#1F1F28"
intensity = "Bold"

[metadata]
name = "kanagawa-paper-ink-lightened"
author = "donniebreve"
