[window]
title = "Alacritty"

[window.dimensions]
columns = 128
lines = 36

[font]
size = 11.0

[font.normal]
family = "JetBrains Mono"

[terminal.shell]
program = "/bin/fish"

[general]
import = ["themes/kanagawa-paper.toml"]
